// Package cors provides JWT helper utilities and example Gin handlers used by Doiit services.
//
// The package is intentionally small and is designed for two common use cases:
//
//   - issuing JWT access tokens after a successful login or service-to-service authentication flow
//   - reading authenticated user data from Gin context in protected routes
//
// Typical usage looks like this:
//
//	router := gin.New()
//	router.GET("/login", func(c *gin.Context) {
//	    token, err := cors.GenerateJWT("user-123", "user@example.com", []string{"admin"})
//	    if err != nil {
//	        c.JSON(http.StatusInternalServerError, gin.H{"error": "could not create token"})
//	        return
//	    }
//
//	    c.JSON(http.StatusOK, gin.H{"token": token})
//	})
//
//	router.GET("/me", authMiddleware(), cors.ProtectedHandler)
//
// The package expects the calling service to configure the JWT secret and issuer settings
// through the shared config package before generating tokens.
package cors

import (
	"crypto/rand"
	"encoding/base64"
	"net/http"
	"time"

	"github.com/fasunle/doiitware/config"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
)

// Claims represents the custom JWT claims embedded in tokens generated by GenerateJWT.
//
// The registered claims are populated with the issuer, audience, subject, issue time,
// validity window, and token ID used by Doiit services.
type Claims struct {
	UserID   string   `json:"user_id"`
	Email    string   `json:"email"`
	Roles    []string `json:"roles"`
	ClientID string   `json:"client_id,omitempty"`
	jwt.RegisteredClaims
}

var jwtSecret []byte

// ProtectedHandler returns a simple JSON response for a protected Gin route.
//
// It expects upstream middleware to have already authenticated the request and stored
// the following values in the Gin context:
//   - user_id
//   - email
//   - roles
//
// Example:
//
//	router.GET("/me", authMiddleware(), cors.ProtectedHandler)
func ProtectedHandler(c *gin.Context) {
	userID := c.GetString("user_id")
	email := c.GetString("email")
	roles := c.GetStringSlice("roles")

	c.JSON(http.StatusOK, gin.H{
		"message": "Welcome to the protected endpoint!",
		"user": gin.H{
			"id":    userID,
			"email": email,
			"roles": roles,
		},
	})
}

// GenerateJWT creates and signs a new JWT access token.
//
// The token uses HS512 signing and includes the configured issuer, audience, and expiry
// from the shared config package. The resulting token is suitable for:
//
//   - login responses from an authentication endpoint
//   - short-lived service tokens for internal requests
//   - tests or local development where a predictable token structure is useful
//
// Example:
//
//	token, err := cors.GenerateJWT("user-123", "user@example.com", []string{"admin"})
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	fmt.Println(token)
func GenerateJWT(userID, email string, roles []string) (string, error) {
	claims := Claims{
		UserID: userID,
		Email:  email,
		Roles:  roles,
		RegisteredClaims: jwt.RegisteredClaims{
			Issuer:    config.JwtIssuer,
			Audience:  []string{config.JwtAudience},
			Subject:   userID,
			IssuedAt:  jwt.NewNumericDate(time.Now()),
			NotBefore: jwt.NewNumericDate(time.Now()),
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(config.JwtExpiry)),
			ID:        generateTokenID(),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS512, claims)
	return token.SignedString(jwtSecret)
}

// generateTokenID creates a unique token ID for the JWT jti claim.
func generateTokenID() string {
	b := make([]byte, 32)
	rand.Read(b)
	return base64.URLEncoding.EncodeToString(b)
}
